
export const endpointsData = [




  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a toke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
   
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: false,
   
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
   
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: false,
   
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: true,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: true,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: true,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: true,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: false,
  },

  // luego añadimos más...
];
