// export const endpointsData = [
//  {
//     id: 0,
//     image: "/cards/chuck.jpg",
//     baseUrl: "https://picsum.photos/300/140",
//   },

//   {
//     id: 1,
//     image: "https://picsum.photos/300/140",
//     baseUrl: "https://picsum.photos/300/140",
//   },
//   {
//     id: 2,
//     image: "https://picsum.photos/200/140",
//     baseUrl: "https://picsum.photos/300/140",
//   },
//   {
//     id: 3,
//     image: "https://picsum.photos/300/100",
//     baseUrl: "https://picsum.photos/300/140",
//   },
//    {
//     id: 4,
//     image: "https://picsum.photos/300/140",
//     baseUrl: "https://picsum.photos/300/140",
//   },
//   {
//     id: 5,
//     image: "https://picsum.photos/200/140",
//     baseUrl: "https://picsum.photos/300/140",
//   },
//   {
//     id: 6,
//     image: "https://picsum.photos/300/100",
//     baseUrl: "https://picsum.photos/300/140",
//   },

//    {
//     id: 7,
//     image: "https://picsum.photos/300/140",
//     baseUrl: "https://picsum.photos/300/140",
//   },
//   {
//     id: 8,
//     image: "https://picsum.photos/200/140",
//     baseUrl: "https://picsum.photos/300/140",
//   },
//   {
//     id: 9,
//     image: "https://picsum.photos/300/100",
//     baseUrl: "https://picsum.photos/300/140",
//   },
//    {
//     id: 10,
//     image: "https://picsum.photos/300/140",
//     baseUrl: "https://picsum.photos/300/140",
//   },
//   {
//     id: 11,
//     image: "https://picsum.photos/200/140",
//     baseUrl: "https://picsum.photos/300/140",
//   },
//   {
//     id: 12,
//     image: "https://picsum.photos/300/100",
//     baseUrl: "https://picsum.photos/300/140",
//   },
// ];

export const endpointsData = [
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: true,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: true,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: true,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: true,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: 1,
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: false,
  },

  // luego añadimos más...
];
