export const endpointsData = [
  {
    id: "1",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "1. You get a toke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: "2",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "2. You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: false,
  },
  {
    id: "3",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "3. You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: "4",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "4. You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: false,
  },
  {
    id: "5",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "5. You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: true,
  },
  {
    id: "6",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "6. You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: "7",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "7. You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: "8",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "8. You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: false,
  },
  {
    id: "9",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "9. You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: true,
  },
  {
    id: "10",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "10. You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: true,
  },
  {
    id: "11",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "11. You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: "12",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "12. You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: true,
  },
  {
    id: "13",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "13. You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: true,
    hasParams: false,
  },
  {
    id: "14",
    image: "/cards/chuck.jpg",
    baseUrl: "https://api.chucknorris.io",
    endpoint: "/jokes/random",
    description: "14. You get a joke inspired in Chuck Norris:",
    exampleData: `"dylan hallmark beat Chuck Norris up"`,
    requiresApiKey: false,
    hasParams: false,
  },
];
